#!/usr/bin/env python3
"""Render matrix.gen.hcl and CI matrices from matrix.json.

matrix.json is the source of truth. bake cannot read JSON from disk, so this
renders an HCL variable it can consume. Both files are committed and CI runs
--check to fail on drift.
"""
import argparse
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import pgo_tiers  # noqa: E402  -- same directory, and the only source of tier membership

ROOT = Path(__file__).resolve().parent.parent
MATRIX = ROOT / "matrix.json"
GENERATED = ROOT / "matrix.gen.hcl"
HEADER = "# generated by scripts/gen_matrix.py from matrix.json -- do not edit\n"


def load():
    return json.loads(MATRIX.read_text())


VALID_SUPPORT = {"active", "security", "end-of-life"}
_DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")


def validate_support_fields(matrix):
    """support/eol_date feed straight into published image labels
    (docker-bake.hcl) -- a typo here would silently ship a wrong one.
    """
    versions = matrix["versions"]
    for php, spec in versions.items():
        support = spec.get("support")
        if support not in VALID_SUPPORT:
            raise SystemExit(
                f"matrix.json: {php}.support={support!r} must be one of {sorted(VALID_SUPPORT)}"
            )
        eol_date = spec.get("eol_date")
        if not isinstance(eol_date, str) or not _DATE_RE.match(eol_date):
            raise SystemExit(f"matrix.json: {php}.eol_date={eol_date!r} must be YYYY-MM-DD")


def target_name(php, flavor, uarch):
    slug = php.replace(".", "_")
    suffix = "-v3" if uarch == "v3" else ""
    return f"php-{slug}-{flavor}{suffix}"


def tags_for(matrix, php, flavor, uarch):
    image = matrix["image"]
    if uarch == "v3":
        return [f"{image}:{php}-{flavor}-v3"]
    tags = [f"{image}:{php}-{flavor}"]
    if php == matrix["default_version"] and flavor == "fpm":
        tags += [f"{image}:{php}", f"{image}:latest"]
    return tags


def corpus_tags(matrix):
    """The PGO corpus image tag each version's build mounts, keyed by version.

    Derived from scripts/pgo_tiers.py -- the same module php/pgo/corpus's
    build and update-locks scripts read -- so the tag is a function of
    matrix.json and php/pgo/corpus/tiers, never a second copy of the mapping.
    Every version gets one, including the pgo=false ones: the Dockerfile mounts
    the corpus unconditionally (a conditional mount is not expressible, and a
    placeholder image for the fallback case would mean the two paths stop being
    the same code).
    """
    _matrix, known, rows = pgo_tiers.table()
    tags = {}
    for php in matrix["versions"]:
        floor = pgo_tiers.tier_of(php, known)
        if floor is None:
            raise SystemExit(
                f"no corpus tier covers php {php} (lowest floor is {min(known, key=pgo_tiers.key)}) "
                f"-- add a floor to php/pgo/corpus/tiers"
            )
        tags[php] = rows[floor]["tag"]
    return tags


def build_targets(matrix):
    """One entry per published image. 33 baseline + 6 v3 = 39."""
    tags = corpus_tags(matrix)
    targets = []
    for php, spec in matrix["versions"].items():
        for uarch in spec["uarch"]:
            for flavor in matrix["flavors"]:
                targets.append({
                    "name": target_name(php, flavor, uarch),
                    "php": php,
                    "release": spec["release"],
                    "era": spec["era"],
                    "flavor": flavor,
                    "uarch": uarch,
                    "compiler": spec["compiler"],
                    "pgo": "true" if spec["pgo"] else "false",
                    "icu": spec["icu"] or "",
                    "corpus": tags[php],
                    "tags": tags_for(matrix, php, flavor, uarch),
                    "platforms": matrix["platforms"],
                    "support": spec["support"],
                    "eol_date": spec["eol_date"],
                })
    return targets


def build_bootstrap_targets(matrix):
    """One cli-builder entry per corpus tier floor (task 37c).

    A from-zero environment has no cli-builder image and no corpus image, and
    each depends on the other: a tier's corpus is built from that tier
    floor's cli-builder, and every php build (including a cli-builder) mounts
    a corpus. These targets break that cycle -- PGO=false, baseline uarch
    only, built against the placeholder corpus in
    php/pgo/Dockerfile.bootstrap-corpus instead of a real one -- so
    tests/build-corpus.sh always has something to build a tier's real corpus
    from. Never part of build_targets()/the release matrix: distinct name and
    tag suffix, plus the com.lotuswebagency.bootstrap label docker-bake.hcl
    adds, keep it from ever being mistaken for or published as one.

    Floors, not versions: five entries regardless of how many matrix.json
    versions a tier serves, from the same scripts/pgo_tiers.py floor list
    tests/build-corpus.sh already iterates.
    """
    _matrix, known, _rows = pgo_tiers.table()
    targets = []
    for floor in sorted(known, key=pgo_tiers.key):
        spec = matrix["versions"][floor]
        targets.append({
            "name": target_name(floor, "cli-builder", "baseline") + "-bootstrap",
            "php": floor,
            "release": spec["release"],
            "era": spec["era"],
            "compiler": spec["compiler"],
            "icu": spec["icu"] or "",
        })
    return targets


def build_compile_jobs(matrix):
    """One entry per distinct compile: version x uarch x arch. 26 total."""
    jobs = []
    for php, spec in matrix["versions"].items():
        for uarch in spec["uarch"]:
            for platform in matrix["platforms"]:
                jobs.append({"php": php, "uarch": uarch, "platform": platform})
    return jobs


def hcl_value(value):
    if isinstance(value, list):
        return "[" + ", ".join(hcl_value(v) for v in value) + "]"
    return json.dumps(value)


def render(matrix):
    lines = [HEADER, 'variable "TARGETS" {\n', "  default = [\n"]
    for t in build_targets(matrix):
        fields = ", ".join(f"{k} = {hcl_value(v)}" for k, v in t.items())
        lines.append(f"    {{ {fields} }},\n")
    lines += ["  ]\n", "}\n", "\n"]
    lines += ['variable "BOOTSTRAP_TARGETS" {\n', "  default = [\n"]
    for t in build_bootstrap_targets(matrix):
        fields = ", ".join(f"{k} = {hcl_value(v)}" for k, v in t.items())
        lines.append(f"    {{ {fields} }},\n")
    lines += ["  ]\n", "}\n", "\n"]
    lines += [f'variable "BASE_IMAGE" {{ default = {json.dumps(matrix["base"])} }}\n']
    return "".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="exit 1 if generated file is stale")
    parser.add_argument("--github", choices=["targets", "compile", "pr"], help="print a GitHub Actions matrix")
    args = parser.parse_args()
    matrix = load()
    validate_support_fields(matrix)

    if args.github == "targets":
        print(json.dumps({"include": build_targets(matrix)}))
        return 0
    if args.github == "compile":
        print(json.dumps({"include": build_compile_jobs(matrix)}))
        return 0
    if args.github == "pr":
        subset = {"php-7_0-fpm", "php-8_2-fpm", "php-8_5-fpm", "php-8_5-cli-builder"}
        include = [t for t in build_targets(matrix) if t["name"] in subset]
        print(json.dumps({"include": include}))
        return 0

    rendered = render(matrix)
    if args.check:
        current = GENERATED.read_text() if GENERATED.exists() else ""
        if current != rendered:
            print("matrix.gen.hcl is stale; run: python3 scripts/gen_matrix.py", file=sys.stderr)
            return 1
        return 0

    GENERATED.write_text(rendered)
    print(f"wrote {GENERATED.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
