#!/usr/bin/env python3
"""Render matrix.gen.hcl and CI matrices from matrix.json.

matrix.json is the source of truth. bake cannot read JSON from disk, so this
renders an HCL variable it can consume. Both files are committed and CI runs
--check to fail on drift.
"""
import argparse
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import pgo_tiers  # noqa: E402  -- sole source of tier membership

ROOT = Path(__file__).resolve().parent.parent
MATRIX = ROOT / "matrix.json"
GENERATED = ROOT / "matrix.gen.hcl"
HEADER = "# generated by scripts/gen_matrix.py from matrix.json -- do not edit\n"


def load():
    return json.loads(MATRIX.read_text())


VALID_SUPPORT = {"active", "security", "end-of-life"}
_DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")


def validate_baseline_only_flavors(matrix):
    unknown = set(matrix.get("baseline_only_flavors", [])) - set(matrix["flavors"])
    if unknown:
        raise SystemExit(f"matrix.json: baseline_only_flavors {sorted(unknown)} are not in flavors")


def validate_support_fields(matrix):
    """support/eol_date become published image labels (docker-bake.hcl)."""
    versions = matrix["versions"]
    for php, spec in versions.items():
        support = spec.get("support")
        if support not in VALID_SUPPORT:
            raise SystemExit(
                f"matrix.json: {php}.support={support!r} must be one of {sorted(VALID_SUPPORT)}"
            )
        eol_date = spec.get("eol_date")
        if not isinstance(eol_date, str) or not _DATE_RE.match(eol_date):
            raise SystemExit(f"matrix.json: {php}.eol_date={eol_date!r} must be YYYY-MM-DD")


def target_name(php, flavor, uarch):
    slug = php.replace(".", "_")
    suffix = "-v3" if uarch == "v3" else ""
    return f"php-{slug}-{flavor}{suffix}"


def tags_for(matrix, php, flavor, uarch):
    image = matrix["image"]
    if uarch == "v3":
        return [f"{image}:{php}-{flavor}-v3"]
    tags = [f"{image}:{php}-{flavor}"]
    if php == matrix["default_version"] and flavor == "fpm":
        tags += [f"{image}:{php}", f"{image}:latest"]
    return tags


def corpus_tags(matrix):
    """The PGO corpus image tag each version's build mounts, keyed by version.

    Derived from scripts/pgo_tiers.py, so the tag is a function of matrix.json
    and php/pgo/corpus/tiers. Every version gets one, including pgo=false
    ones: the Dockerfile mounts the corpus unconditionally.
    """
    _matrix, known, rows = pgo_tiers.table()
    tags = {}
    for php in matrix["versions"]:
        floor = pgo_tiers.tier_of(php, known)
        if floor is None:
            raise SystemExit(
                f"no corpus tier covers php {php} (lowest floor is {min(known, key=pgo_tiers.key)}) "
                f"-- add a floor to php/pgo/corpus/tiers"
            )
        tags[php] = rows[floor]["tag"]
    return tags


def build_targets(matrix):
    """One entry per published image. 44 baseline + 6 v3 = 50.

    Flavors in baseline_only_flavors (ext-builder) get no v3 variant: an
    extension built against baseline headers loads on the v3 runtime.
    """
    baseline_only = set(matrix.get("baseline_only_flavors", []))
    tags = corpus_tags(matrix)
    targets = []
    for php, spec in matrix["versions"].items():
        for uarch in spec["uarch"]:
            for flavor in matrix["flavors"]:
                if uarch != "baseline" and flavor in baseline_only:
                    continue
                targets.append({
                    "name": target_name(php, flavor, uarch),
                    "php": php,
                    "release": spec["release"],
                    "era": spec["era"],
                    "flavor": flavor,
                    "uarch": uarch,
                    "compiler": spec["compiler"],
                    "pgo": "true" if spec["pgo"] else "false",
                    "icu": spec["icu"] or "",
                    "corpus": tags[php],
                    "cache_flavor": RIDES_WITH.get(flavor, flavor),
                    "tags": tags_for(matrix, php, flavor, uarch),
                    "platforms": matrix["platforms"],
                    "support": spec["support"],
                    "eol_date": spec["eol_date"],
                })
    return targets


def build_bootstrap_targets(matrix):
    """One cli-builder entry per corpus tier floor.

    A tier's corpus is built from that floor's cli-builder, and every php build
    mounts a corpus. These targets break the cycle: PGO=false, baseline uarch,
    built against the placeholder corpus in php/pgo/Dockerfile.bootstrap-corpus.
    They are never part of the release matrix; the distinct name and tag suffix
    and the com.lotuswebagency.bootstrap label keep them from being published.
    """
    _matrix, known, _rows = pgo_tiers.table()
    targets = []
    for floor in sorted(known, key=pgo_tiers.key):
        spec = matrix["versions"][floor]
        targets.append({
            "name": target_name(floor, "cli-builder", "baseline") + "-bootstrap",
            "php": floor,
            "release": spec["release"],
            "era": spec["era"],
            "compiler": spec["compiler"],
            "icu": spec["icu"] or "",
        })
    return targets


# A flavor listed here is built in the same bake invocation as the flavor it
# maps to, for the same php/uarch. ext-builder is `FROM cli` and copies out of
# the same php-build stage, but each CI leg has its own cache scope and runner,
# so a leg of its own would recompile PHP and re-run PGO.
RIDES_WITH = {"ext-builder": "cli"}

PR_SUBSET = {
    "php-7_0-fpm", "php-8_2-fpm", "php-8_5-fpm", "php-8_5-cli-builder",
    "php-8_5-cli", "php-8_5-ext-builder",
}


def build_legs(targets):
    """Group image targets into CI build legs: one bake invocation each.

    A leg is the host target's entry plus `rider_name` / `rider_flavor` /
    `rider_tag` (all "" when there is no rider, so matrix expressions need no
    null check) and `bake`, the space-separated bake target names to build
    together. Riders get no leg of their own, which keeps one php-build per leg
    while `--github targets` still lists every target.
    """
    by_key = {(t["php"], t["uarch"], t["flavor"]): t for t in targets}
    riders = {}
    for t in targets:
        host_flavor = RIDES_WITH.get(t["flavor"])
        if host_flavor is None:
            continue
        host = (t["php"], t["uarch"], host_flavor)
        if host not in by_key:
            raise SystemExit(
                f"{t['name']} rides with {host_flavor}, but there is no {host_flavor} target "
                f"for php {t['php']} ({t['uarch']}) in this selection"
            )
        riders[host] = t
    legs = []
    for t in targets:
        if t["flavor"] in RIDES_WITH:
            continue
        rider = riders.get((t["php"], t["uarch"], t["flavor"]))
        leg = dict(t)
        leg["rider_name"] = rider["name"] if rider else ""
        leg["rider_flavor"] = rider["flavor"] if rider else ""
        leg["rider_tag"] = rider["tags"][0] if rider else ""
        leg["bake"] = " ".join([t["name"]] + ([rider["name"]] if rider else []))
        legs.append(leg)
    return legs


def build_compile_jobs(matrix):
    """One entry per distinct compile: version x uarch x arch. 26 total."""
    jobs = []
    for php, spec in matrix["versions"].items():
        for uarch in spec["uarch"]:
            for platform in matrix["platforms"]:
                jobs.append({"php": php, "uarch": uarch, "platform": platform})
    return jobs


def hcl_value(value):
    if isinstance(value, list):
        return "[" + ", ".join(hcl_value(v) for v in value) + "]"
    return json.dumps(value)


def render(matrix):
    lines = [HEADER, 'variable "TARGETS" {\n', "  default = [\n"]
    for t in build_targets(matrix):
        fields = ", ".join(f"{k} = {hcl_value(v)}" for k, v in t.items())
        lines.append(f"    {{ {fields} }},\n")
    lines += ["  ]\n", "}\n", "\n"]
    lines += ['variable "BOOTSTRAP_TARGETS" {\n', "  default = [\n"]
    for t in build_bootstrap_targets(matrix):
        fields = ", ".join(f"{k} = {hcl_value(v)}" for k, v in t.items())
        lines.append(f"    {{ {fields} }},\n")
    lines += ["  ]\n", "}\n", "\n"]
    lines += [f'variable "BASE_IMAGE" {{ default = {json.dumps(matrix["base"])} }}\n']
    return "".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="exit 1 if generated file is stale")
    parser.add_argument("--github", choices=["targets", "build", "compile", "pr"], help="print a GitHub Actions matrix")
    args = parser.parse_args()
    matrix = load()
    validate_support_fields(matrix)
    validate_baseline_only_flavors(matrix)

    if args.github == "targets":
        print(json.dumps({"include": build_targets(matrix)}))
        return 0
    if args.github == "build":
        print(json.dumps({"include": build_legs(build_targets(matrix))}))
        return 0
    if args.github == "compile":
        print(json.dumps({"include": build_compile_jobs(matrix)}))
        return 0
    if args.github == "pr":
        include = build_legs([t for t in build_targets(matrix) if t["name"] in PR_SUBSET])
        print(json.dumps({"include": include}))
        return 0

    rendered = render(matrix)
    if args.check:
        current = GENERATED.read_text() if GENERATED.exists() else ""
        if current != rendered:
            print("matrix.gen.hcl is stale; run: python3 scripts/gen_matrix.py", file=sys.stderr)
            return 1
        return 0

    GENERATED.write_text(rendered)
    print(f"wrote {GENERATED.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
